name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Increment (patch, minor, major)"
        required: true
        default: "patch"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run release ${{ github.event.inputs.increment }} --ci
        env:
          CI: true
